name: Create Plugin Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: zip
          
      - name: Install Composer dependencies (production only)
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --optimize-autoloader --no-interaction
          fi
          
      - name: Build plugin package
        run: |
          # Create build directory
          mkdir -p build/coupon-manager
          
          # Copy production files
          cp -r assets build/coupon-manager/
          cp -r views build/coupon-manager/
          cp -r vendor build/coupon-manager/ 2>/dev/null || true
          cp gf-coupon-generator.php build/coupon-manager/
          cp README.md build/coupon-manager/
          
          # Create the plugin zip
          cd build
          zip -r coupon-manager-plugin.zip coupon-manager/
          
      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create the release with the plugin package attached
          gh release create ${{ steps.get_tag.outputs.TAG_NAME }} \
            --title "GravityForms Coupon Manager ${{ steps.get_tag.outputs.TAG_NAME }}" \
            --notes "## GravityForms Coupon Manager ${{ steps.get_tag.outputs.TAG_NAME }}

          ### Installation
          1. Download the \`coupon-manager-plugin.zip\` file below
          2. Go to WordPress Admin → Plugins → Add New → Upload Plugin
          3. Choose the downloaded zip file and install
          4. Activate the plugin

          ### Changes
          See the commit history for detailed changes in this release.

          ### Requirements
          - WordPress 5.0+
          - Gravity Forms plugin
          - Gravity Forms Coupons Add-On
          - PHP 8.1+" \
            ./build/coupon-manager-plugin.zip 